### ISSUE TITLE
`IndexError: list index out of range` when FreeProxy().get()

### ISSUE THREAD

**Issue by yasserqureshi1** [jundymek/free-proxy#15]
I get the an `IndexError` when after using the `.get()` method. Below is an example:

```
>> from fp.fp import FreeProxy
>> obj = FreeProxy(country_id=['US'])
>> obj.get()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/fp/fp.py", line 38, in get
    proxy_list = self.get_proxy_list()
  File "/usr/local/lib/python3.8/dist-packages/fp/fp.py", line 28, in get_proxy_list
    proxies = [f'{tr_elements[i][0].text_content()}:{tr_elements[i][1].text_content()}' for i in
  File "/usr/local/lib/python3.8/dist-packages/fp/fp.py", line 30, in <listcomp>
    if tr_elements[i][2].text_content() in self.country_id
IndexError: list index out of range
```

**Comment by jundymek** [comment]
I am closing this issue. I hope @vkraut fix helped.
